# Generated by Django 4.0.5 on 2022-06-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_alter_board_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='done',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('TODO', 'Todo'), ('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], default='TODO', max_length=25),
        ),
    ]
