# Generated by Django 4.0.5 on 2022-06-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_remove_todoitem_done_todoitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='end',
        ),
    ]
